name: TechStack-NER
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - attrs==25.1.0
      - black==25.1.0
      - bleach==6.2.0
      - blis==1.2.0
      - catalogue==2.0.10
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - contourpy==1.3.1
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==3.2.0
      - dill==0.3.8
      - en-core-web-sm==3.8.0
      - evaluate==0.4.3
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - huggingface-hub==0.28.1
      - idna==3.10
      - isort==6.0.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - kaggle==1.7.4.2
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - loguru==0.7.3
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.1.0
      - platformdirs==4.3.6
      - preshed==3.0.9
      - propcache==0.2.1
      - protobuf==6.30.1
      - pyarrow==19.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - python-slugify==8.0.4
      - pytz==2025.1
      - pyyaml==6.0.2
      - rapidfuzz==3.12.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - ruff==0.9.4
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - seqeval==1.2.2
      - shellingham==1.5.4
      - smart-open==7.1.0
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.13.1
      - text-unidecode==1.3
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.48.2
      - triton==3.2.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - webencodings==0.5.1
      - wordninja==2.0.0
      - wordsegment==1.3.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: /home/whilebell/anaconda3/envs/TechStack-NER
